# Generated by Django 4.1.5 on 2023-01-10 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subCategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6fa9f49-a1f3-4a3b-a9ff-b06c0ab22578'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d210090-2b19-447a-98f6-9311067d941e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b02bf0e7-7ea1-4f0b-9de3-00a5274c1a20'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be90a571-63f4-41b8-802e-29d8d97c79cd'), primary_key=True, serialize=False),
        ),
    ]
