# Generated by Django 4.1.5 on 2023-01-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='small_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
