# Generated by Django 4.1.5 on 2023-01-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_country_id_alter_province_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraddresses',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraddresses',
            name='province',
        ),
        migrations.RemoveField(
            model_name='useraddresses',
            name='user',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='UserAddresses',
        ),
    ]
